name: Bug Report
description: Something wrong in executing the examples
title: "[Bug]: "
labels: ["bug"]
assignees:
  - cric96
  - metaphori
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: os
    attributes:
      label: What OS are you using? (e.g., Windows 11, MacOS Catalina, ...)?
      value: "Windows 11"
  - type: textarea
    id: jave-version
    attributes:
      label: What is you java version? (type java -version in the terminal)
      value: "Java 11"
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
